### PR TITLE
*/*: fix redirection

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

For some time now ```www.kde.org``` redirects to ```kde.org```. This PR updates all affected ebuilds to reflect this change. However, i know this is not a real problem as it doesn't really fix anything, which is why i also made a single commit for the changes. I'm ok if this PR won't get merged, but it would be nice if we could fix this :)

Please review.

### CODE REVIEW

**Comment by mm1ke** [comment]
@a17r 
Updated, i already had the eclass included but i put it in a separate commit now. :)

**Comment by a17r** [comment]
> @a17r
> Updated, i already had the eclass included but i put it in a separate commit now. :)

Thanks, correct prefix for eclasses is: `kde5.eclass: `...

**Comment by mm1ke** [comment]
> > @a17r
> > Updated, i already had the eclass included but i put it in a separate commit now. :)
> 
> Thanks, correct prefix for eclasses is: `kde5.eclass: `...

Fixed :)

**Comment by a17r** [comment]
Thanks, please don't forget sign-off next time.

**Pull request closed without merging**
