### PR TITLE
kde-apps/kdepim-addons-9999: Change "comment_add_subdirectory" to match EAPI6

### PR DESCRIPTION
**Pull request by frames**
kde-apps/kdepim-addons-9999: Changed "comment_add_subdirectory" to "cmake_comment_add_subdirectory"

### CODE REVIEW

**Comment by frames** [comment]
Apologies for the messy comment: My first commit EVER!

**Comment by johu** [comment]
Thanks for spotting the issue. You will need to add the change to the stable branch ebuild as well. Could you please shorten the commit subject to "kde-apps/kdepim-addons: Fix src_prepare". You can put the longer description in the commit message body.

**Comment by frames** [comment]
Thanks for the info.

**Comment by johu** [comment]
Could you please adjust the commit (rebase + force push will be needed in your branch)?

**Comment by johu** [comment]
Thanks fixed in e1b0e2075c87951002f662c3fb6db9e0c9c82159

**Pull request closed without merging**
