### PR TITLE
[kde-plasma/plasma-workspace] Add dev-qt/qtconcurrent (upstream a462d12)

### PR DESCRIPTION
**Pull request by eliasp**
Package-Manager: portage-2.2.17

### CODE REVIEW

**Comment by johu** [comment]
I can not find any linking against qtconcurrent. Upstream issue of not needed dependency?

**Comment by eliasp** [comment]
Sorry, had a typo in the commit ID in the title.
The [commit](http://quickgit.kde.org/?p=plasma-workspace.git&a=commitdiff&h=a462d12ab9bfdb11f6b3c418f2abdd6f06f773f5) which should've introduced this dependency.

QtConcurrent is listed in the link libraries and the code also makes use of it - no idea why the built code doesn't seem to link against QtConcurrent.

**Comment by kensington** [comment]
I've seen a lot of similar QtConcurrent usage across various KDE stuff that never ends up in NEEDED. I never checked, but I guess it ends up getting inlined/optimised.

**Comment by johu** [comment]
Thanks. Rebased with reworded commit message onto kde overlay master.

**Pull request closed without merging**
