### PR TITLE
kde-apps/ktp-l10n: Add blocker on <kde-apps/kde-l10n-16.08.0

### PR DESCRIPTION
**Pull request by MJDSys**
There are a number of files that changed packages between 16.04 and 16.08.
Add a blocker to get the update to work correctly.

Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by a17r** [comment]
What blockers are there?

**Comment by MJDSys** [comment]
I don't have the list anymore, but it had to do with the sr files.  kde-l10n-16.04 had some ktp related translation files, and after adding this change both have installed successfully.

If you want, I can try to reproduce and submit the list.

**Comment by a17r** [comment]
This seems indeed related to L10N=sr splitting that was introduced with 16.04.3. The correct blocker should be <16.04.3 then, and also be added to kdepim-l10n, and may better be backported to tree as well.

**Comment by MJDSys** [comment]
So it appears you are correct, trying to go from 16.04.2 to 16.04.3 gives the same result (see https://gist.github.com/MJDSys/57b986d345be07858b200867131b1174 for details).  kdepim-l10n-16.04.2 won't even install due to conflicts.

I think the simple answer is that 16.04.2's l10n has some problems, and the easiest thing to do is add conflicts for both ktp and kdepim to both 16.04.3 and 16.08.0.  That way anyone upgrading will get the right solution.  I'll update this PR, and if you are happy submit one against gentoo/gentoo as well.

**Comment by a17r** [comment]
Thanks for fixing this! PR looks good except for that one bogus k3b commit that sneaked into it ;)

**Comment by MJDSys** [comment]
@a17r That is from the kde repo hosted by gentoo.  It apparently hasn't been synced to github yet.

I'll submit a PR against main for 16.04.3.

**Comment by kensington** [comment]
Thanks, picked as 076dffa869ba6536e223556755ebddf0e631d394...36e8a8179e1036075d1d73f175a0284e14c8d396.

**Pull request closed without merging**
