### PR TITLE
[kde-base/libkgreeter] New ebuild wrt bug #520236

### PR DESCRIPTION
**Pull request by a17r**
* Make kde-base/kdm really optional
* Resolve block between kde-apps/kdepasswd and kde-base/kdepasswd

### CODE REVIEW

**Comment by johu** [comment]
Please handle Documentation changes properly. Update sets and then run regenerate files script. The manual manipulation commits have to dropped.

**Comment by a17r** [comment]
That's what I did with kdebase-workspace-4.11 and 10 files were properly regenerated, but sets/kdebase-workspace was not (and I didn't find what other set could be responsible for it)?

**Comment by johu** [comment]
Edit kdebase-workspace-4.11 set, run script.

**Comment by johu** [comment]
You may need to adjust the script locally RELEASE=${RELEASE:-4.11}

**Comment by a17r** [comment]
Indeed, that did the trick. Thanks!

**Comment by johu** [comment]
Please squash those libkgreater commits to one.

**Comment by a17r** [comment]
Patches now properly split and squashed.

**Comment by johu** [comment]
Thanks. This is rebased onto kde overlay master.

**Pull request closed without merging**
