### PR TITLE
[app-cdr/k3b] fix failing patch when USE=-handbook

### PR DESCRIPTION
**Pull request by karolherbst**
Package-Manager: portage-2.2.17

### CODE REVIEW

**Comment by a17r** [comment]
Strange, it works for me...

**Comment by karolherbst** [comment]
I think it is a doc issue. the add_subdirectory( doc ) line is getting commented out and this triggers the epatch failure then.

**Comment by karolherbst** [comment]
yeah, I tested it.
bug with USE=-handbook
no bug with USE=handbook

**Comment by johu** [comment]
Thanks. This is rebased onto kde overlay master.

**Pull request closed without merging**
