### PR TITLE
[kde-plasma/plasma-workspace] Update startkde Gentoo FHS patch

### PR DESCRIPTION
**Pull request by eliasp**
Package-Manager: portage-2.2.20

### CODE REVIEW

**Comment by eliasp** [comment]
Sorry, ignore this one for a moment. Needs some corrections.

**Comment by johu** [comment]
Does it work with 5.3?

**Comment by eliasp** [comment]
You're right - I thought this was only pulled in by `-9999`.
None of `5.3.x` is compatible.

Updated the PR accordingly.

**Comment by johu** [comment]
Thanks for your work!

**Pull request merged**
