### PR TITLE
Remove obsolete dependency

### PR DESCRIPTION
**Pull request by kingfared**
https://invent.kde.org/network/ktorrent/-/commit/fc252072d38f1d7380cd9807b44881bffebe527c

### CODE REVIEW

**Comment by thesamesam** [comment]
Please stick to the commit message convention for the repo (`cat/name: ...`) and include `Signed-off-by`. Thanks.

**Comment by thesamesam** [comment]
...?

**Comment by kingfared** [comment]
I'll delete and resend again

**Comment by thesamesam** [comment]
It's ok to force push to PRs, fwiw.

**Pull request closed without merging**
