### PR TITLE
Add missing remote-id's

### PR DESCRIPTION
**Pull request by parona-source**
Some low hanging fruit.

This is just what pkgcheck reports, so packages without non live packages are missed (pkgcheck only checks SRC_URI and HOMEPAGE for the check).

### CODE REVIEW

**Comment by a17r** [comment]
lgtm, thanks for doing this - still working on it (hence draft)?

**Comment by parona-source** [comment]
Just removed the bugs-to as ksanescore didnt have product page there.

Also I guess NonexistentBlocker would be a good candidate to ignore globally.

**Comment by a17r** [comment]
Do you have some automatism for this? If yes, you could locally temporarily change *.kde.org eclasses to always set HOMEPAGE and gobble up results.

**Comment by parona-source** [comment]
I could, ideally pkgcheck would be able to use EGIT_REPO_URI but that may be more involved.

**Comment by a17r** [comment]
> Also I guess NonexistentBlocker would be a good candidate to ignore globally in pkgcheck.

That's actually a pkgcheck bug when you're in a branch.

**Pull request closed without merging**
