### PR TITLE
[media-libs/prison] Build the correct live branch

### PR DESCRIPTION
**Pull request by eliasp**
Package-Manager: portage-2.2.17

### CODE REVIEW

**Comment by johu** [comment]
If you switch the branch you'll need to make more changes to the ebuild.

**Comment by eliasp** [comment]
`kde-plasma/plasma-workspace` [links now against `KF5Prison`](http://quickgit.kde.org/?p=plasma-workspace.git&a=commitdiff&h=164235cf0d44deb1422be52e2a4919e46237d3ef) (not `Prison` anymore).

`KF5Prison` is not available in `master` but [only in `frameworks`](http://quickgit.kde.org/?p=prison.git&a=commitdiff&h=10f48d85bf5ba78996549569e04461884779d361) of `media-libs/prison`.

At some point in the future, this might be merged back to `master` of `media-libs/prison`, but I think at this point it might even become a `kde-frameworks/prison` - so for now this is IMHO the right solution.

**Comment by kensington** [comment]
plasma-workspace is the only prison:5 consumer we have so far anyway.

**Comment by johu** [comment]
Could you please fix "find_package(Qt5Test ${QT_REQUIRED_VERSION} CONFIG  REQUIRED)" upstream first?

**Comment by johu** [comment]
Fixed in 270d5ec2bb4d2a48fcb03ad3ab095863fc128bb4 to unbreak plasma-workspace.

**Pull request closed without merging**
