### PR TITLE
[WIP] KDE Education app suite updates

### PR DESCRIPTION
**Pull request by awilfox**
This branch contains the work I'm doing to update and tweak the kdeedu suite of apps.  It is *not ready for merge yet*, but I am making the PR now so that the work I am doing can be tracked by the project.

See also my [Gentoo Wiki user page](https://wiki.gentoo.org/wiki/User:Awilfox/KDEdu_Progress) for updates to the Applications page in the Gentoo KDE Wiki.

### CODE REVIEW

**Comment by a17r** [comment]
Could you rebase your changes against git master and squash kanagram changes into one commit?
What about kanagram-15.12.49.9999 and 9999, do they also need updates?

**Comment by awilfox** [comment]
Yes they do, and I have applied those changes into the single commit (along with EAPI bump, tested working on my machine).

**Comment by a17r** [comment]
EAPI switch usually needs a revbump, parley commit should have kde-apps/ category added in commit message, otherwise lgtm :)

**Comment by awilfox** [comment]
I thought revbump was only for on-disk changes.  As far as I can tell, there weren't any bumping kanagram from EAPI=5 to EAPI=6.

I have force-pushed an amended commit message for parley.

**Comment by kensington** [comment]
Thanks! Picked as ca38654b2b785d1468532ed315386b519f61cc77...1db2c44e5f11b868c1152f9a046d5452fa223c53.

**Pull request closed without merging**
