### PR TITLE
Bumps, ports, some fixes

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by kensington** [comment]
Is kjots going to be joining KDE Applications proper?

**Comment by a17r** [comment]
Most likely not, it was split out of the PIM suite because PIM maintainer(s) wouldn't support it any longer, to have a stop-gap kf5-based release that is able to read notes - as long as zanshin is not there.

**Comment by kensington** [comment]
Maybe it belongs in some other category (app-office?) then.

**Comment by a17r** [comment]
I mostly put it there because kjots-4 is in kde-apps/ as well.

**Comment by kensington** [comment]
Thanks, picked as 6d3ab442b506ad899ebee38d324dbd3aca587ca8...17b435e617b0a349ed6de0b37850b8f80bf432f2.

**Comment by kensington** [comment]
test

**Comment by kensington** [comment]
test

**Pull request closed without merging**
