### PR TITLE
dev-util/kdevelop: Version bump to 5.0.0

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by stintel** [comment]
Getting 404 for kdevplatform-5.0.0:
```
>>> Emerging (2 of 4) dev-util/kdevplatform-5.0.0::kde
>>> Downloading 'http://distfiles.gentoo.org/distfiles/kdevplatform-5.0.tar.xz'
--2016-08-22 11:15:04--  http://distfiles.gentoo.org/distfiles/kdevplatform-5.0.tar.xz
Resolving distfiles.gentoo.org... 140.211.166.134, 137.226.34.46, 64.50.236.52, ...
Connecting to distfiles.gentoo.org|140.211.166.134|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-08-22 11:15:05 ERROR 404: Not Found.

>>> Downloading 'http://mirror.csclub.uwaterloo.ca/kde/stable/kdevplatform/5.0.0/src/kdevplatform-5.0.tar.xz'
--2016-08-22 11:15:05--  http://mirror.csclub.uwaterloo.ca/kde/stable/kdevplatform/5.0.0/src/kdevplatform-5.0.tar.xz
Resolving mirror.csclub.uwaterloo.ca... 2620:101:f000:4901:c5c:0:f:1055, 129.97.134.71
Connecting to mirror.csclub.uwaterloo.ca|2620:101:f000:4901:c5c:0:f:1055|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-08-22 11:15:05 ERROR 404: Not Found.

>>> Downloading 'ftp://mirrors.dotsrc.org/kde/stable/kdevplatform/5.0.0/src/kdevplatform-5.0.tar.xz'
pathconf: Permission denied
--2016-08-22 11:15:05--  ftp://mirrors.dotsrc.org/kde/stable/kdevplatform/5.0.0/src/kdevplatform-5.0.tar.xz
           => ‘/usr/portage/distfiles/kdevplatform-5.0.tar.xz’
Resolving mirrors.dotsrc.org... 2001:878:346::116, 130.225.254.116
Connecting to mirrors.dotsrc.org|2001:878:346::116|:21... failed: Connection refused.
Connecting to mirrors.dotsrc.org|130.225.254.116|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /kde/stable/kdevplatform/5.0.0/src ...
No such directory ‘kde/stable/kdevplatform/5.0.0/src’.

>>> Downloading 'ftp://kde.mirror.anlx.net/stable/kdevplatform/5.0.0/src/kdevplatform-5.0.tar.xz'
pathconf: Permission denied
--2016-08-22 11:15:05--  ftp://kde.mirror.anlx.net/stable/kdevplatform/5.0.0/src/kdevplatform-5.0.tar.xz
           => ‘/usr/portage/distfiles/kdevplatform-5.0.tar.xz’
Resolving kde.mirror.anlx.net... 81.91.100.171
Connecting to kde.mirror.anlx.net|81.91.100.171|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /stable/kdevplatform/5.0.0/src ...
No such directory ‘stable/kdevplatform/5.0.0/src’.

>>> Downloading 'http://download.kde.org/stable/kdevplatform/5.0.0/src/kdevplatform-5.0.tar.xz'
--2016-08-22 11:15:06--  http://download.kde.org/stable/kdevplatform/5.0.0/src/kdevplatform-5.0.tar.xz
Resolving download.kde.org... 2001:67c:2178:7::71, 195.135.221.71
Connecting to download.kde.org|2001:67c:2178:7::71|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-08-22 11:15:06 ERROR 404: Not Found.

!!! Couldn't download 'kdevplatform-5.0.tar.xz'. Aborting.
 * Fetch failed for 'dev-util/kdevplatform-5.0.0', Log file:
 *  '/var/tmp/portage/dev-util/kdevplatform-5.0.0/temp/build.log'
```

**Comment by a17r** [comment]
thanks for testing, fixed SRC_URI calculation, should work now.

**Comment by stintel** [comment]
Everything compiles fine now, and a quick runtime test looks OK too. Thanks.

**Comment by a17r** [comment]
USE=!clang was fixed already, upstream patch added

**Comment by kensington** [comment]
Thanks, picked as 5c3d69f0a70eab4783306f10ed171717800f37c5...e2b38fef206ad3a18a5b751eba9ba5e05aa476bd.

**Pull request closed without merging**
