### PR TITLE
added Systemd kcm and latest version of kcmsystemd

### PR DESCRIPTION
**Pull request by karolherbst**
the github repository of kcmsystemd seems to be outdated now and moved to kde git with the new name systemd-kcm

### CODE REVIEW

**Comment by mrueg** [comment]
So we probably should package move kde-misc/kcmsystemd then?

**Comment by karolherbst** [comment]
I am not sure, but I guess so.

kcmsystemd master is KF5 based anyway now (the github repository)

**Comment by karolherbst** [comment]
there are also some tags, I think I will create some more ebuilds before and do the pkgmove

**Comment by karolherbst** [comment]
sadly the github repository wasn't imported into kde git, so that the tags aren't there and we still have to use github for the last stable release, which is 1.1.0 and KF5 based :/

**Comment by johu** [comment]
Thanks. I have just bumped the version.

**Comment by karolherbst** [comment]
@johu what about the live ebuild? It is most likely, that newer version will be called systemd-kcm, because the kde git repository is also named that way?

**Pull request closed without merging**
