### PR TITLE
kde-frameworks: Add 5.19.0 release

### PR DESCRIPTION
**Pull request by a17r**
A little bit too early, but why throw it away... :)

### CODE REVIEW

**Comment by a17r** [comment]
oh, of course - missing digest for lack of access...

**Comment by mrueg** [comment]
How about doing your quizzes instead? That would give you access ;)

**Comment by kensington** [comment]
I'll merge this once I finish squashing EAPI 6 porting on the top.

**Comment by a17r** [comment]
I'd also like to add one patch that sadly didn't make it into kactivities 5.19 anymore.

**Comment by kensington** [comment]
btw, all in-tree versions should have ~arm so the keywording part of the script is broken (if you're using it, that is).

**Comment by kensington** [comment]
Should all now be part of b912038f260872682bec207f6153a26956949dc5...dfe031ff1801e8aee728ebdcccfa7c3ab7df9368.

**Pull request closed without merging**
