### PR TITLE
media-gfx/digikam 4.12.0 version bump

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by a17r** [comment]
one more change, added slot depend to libmediawiki in preparation of :5.

**Comment by johu** [comment]
@akhuettel please review, as it's your maintained package.

**Comment by a17r** [comment]
I'm not so sure about dropping SLOT in kde-apps/libkface - sure it's redundant when using kde4-base, but media-libs/libkface makes use of subslots so maybe some some release in the future would make it necessary in kde-apps/libkface as well (same for other libs).

**Comment by johu** [comment]
But then we then we maybe can find a eclass solution?

**Comment by a17r** [comment]
Yes, especially since there are a few candidates in digikam world for subslots. Also for depending ebuilds, some means to define a slot operator would be nice to have in _add_kdecategory_dep()

**Comment by johu** [comment]
Thanks. Rebased onto kde overlay master. Please keep your quiz in mind.

**Pull request closed without merging**
