### PR TITLE
kde-plasma/plasma-welcome: Remove sed

### PR DESCRIPTION
**Pull request by FireBurn**

### CODE REVIEW

**Comment by a17r** [comment]
Is there a certain upstream commit you can point to in summary?

**Comment by FireBurn** [comment]
https://invent.kde.org/plasma/plasma-welcome/-/commit/7599714403ad369d9b71f568091270840c810f30

**Comment by a17r** [comment]
That means you can drop it from 6.0.49.9999 too. Do it in the same commit, and please add the upstream git commit reference in your git summary.

**Review by a17r — APPROVED** [review]
Thanks!

**Pull request closed without merging**
