### PR TITLE
[kde-base/kdepimlibs] Add USE=minimal to fix block caused by kde-apps/kwalletd

### PR DESCRIPTION
**Pull request by a17r**
At the same time this should go into plasma profile package.use.mask:

kde-base/kdepimlibs:4 minimal -handbook -prison

### CODE REVIEW

**Comment by johu** [comment]
As i know both kwalletd can are co-installable, is this realy needed?

**Comment by a17r** [comment]
kwalletd is co-installable, but the trouble starts when you set USE=gpg, which pulls in kde-base/kdepimlibs:4, and its akonadi stuff collides with kde-apps/kdepimlibs:5

**Comment by johu** [comment]
:-1: On that huge change for disabling one use flag.

**Comment by a17r** [comment]
Wouldn't that make existing gpg wallets from upgrading KDE4 users unusable?

**Comment by a17r** [comment]
Possible alternative:

Introduce kde-apps/legacy-kdepimlibs:4 and make kde-apps/kwalletd:4 depend on it optionally, the blocker on kde-base/kdepimlibs:4 through :5 will settle the dependency and remove the need to touch all those old pim ebuilds.

**Comment by a17r** [comment]
Closing as split package is much better imo.

**Pull request closed without merging**
