### PR TITLE
kde-frameworks/frameworkintegration: plasma now needs noto fonts

### PR DESCRIPTION
**Pull request by Vindex17**
https://quickgit.kde.org/?p=frameworkintegration.git&a=commit&h=3ebe68904cf633ed2fbd4731588d5d4dce2a2b11

### CODE REVIEW

**Comment by kensington** [comment]
Thanks, rebased as 40f2055b133870d2324fbbe4bb7e3735958bd1f6. I'll fix 5.16 in the main tree separately.

**Comment by shiba89** [comment]
Can this be made a useflag? Noto is ~500MB once installed and I don't even plan to use it.

**Comment by kensington** [comment]
@shiba89 Put it in your package.provided. Upstream requires Noto by default and we try to keep as close to upstream as possible.

**Comment by shiba89** [comment]
Seems reasonable. I'll do what you suggested, thank you very much.

**Comment by kensington** [comment]
For a more permanent solution we could consider splitting media-fonts/noto into linguas-specific packages, but that would be up to @gentoo/fonts.

**Comment by minlexx** [comment]
@kensington I heard only chinese or other asian fonts in noto collection consume so much space?

**Comment by kensington** [comment]
@minlexx I think so. Adding some linguas USE flag(s) would allow for substantial reduction in installed space usage, but we might also consider repacking the tarball if download size is also a concern.

**Pull request closed without merging**
