### PR TITLE
kde-frameworks/knotifications: remove qml use flag

### PR DESCRIPTION
**Pull request by parona-source**
* knotifications now has include(ECMQMLModule) which tries to find Qml unconditionally. Leading to a suprisingly unhelpful error when it fails to find it due to -DCMAKE_DISABLE_FIND_PACKAGE_Qt6Qml=ON.

### CODE REVIEW

**Comment by parona-source** [comment]
```
 * Package:    kde-frameworks/knotifications-9999:6/9999
 * Repository: kde
 * Maintainer: kde@gentoo.org
 * Upstream:   https://bugs.kde.org/
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
Initialized empty Git repository in /var/cache/distfiles/git3-src/frameworks_knotifications.git/
 * Repository id: frameworks_knotifications.git
 * To override fetched repository properties, use:
 *   EGIT_OVERRIDE_REPO_FRAMEWORKS_KNOTIFICATIONS
 *   EGIT_OVERRIDE_BRANCH_FRAMEWORKS_KNOTIFICATIONS
 *   EGIT_OVERRIDE_COMMIT_FRAMEWORKS_KNOTIFICATIONS
 *   EGIT_OVERRIDE_COMMIT_DATE_FRAMEWORKS_KNOTIFICATIONS
 * 
 * Fetching https://invent.kde.org/frameworks/knotifications.git ...
git fetch https://invent.kde.org/frameworks/knotifications.git +HEAD:refs/git-r3/HEAD
remote: Enumerating objects: 6473, done.
remote: Counting objects: 100% (1119/1119), done.
remote: Compressing objects: 100% (527/527), done.
remote: Total 6473 (delta 1013), reused 599 (delta 588), pack-reused 5354
Receiving objects: 100% (6473/6473), 8.32 MiB | 2.64 MiB/s, done.
Resolving deltas: 100% (4151/4151), done.
From https://invent.kde.org/frameworks/knotifications
 * [new ref]         HEAD       -> refs/git-r3/HEAD
 * [new tag]         v4.100.0-rc1 -> v4.100.0-rc1
 * [new tag]         v4.95.0    -> v4.95.0
 * [new tag]         v4.96.0    -> v4.96.0
 * [new tag]         v4.97.0    -> v4.97.0
 * [new tag]         v5.100.0   -> v5.100.0
 * [new tag]         v5.100.0-rc1 -> v5.100.0-rc1
 * [new tag]         v5.101.0   -> v5.101.0
 * [new tag]         v5.101.0-rc1 -> v5.101.0-rc1
 * [new tag]         v5.102.0   -> v5.102.0
 * [new tag]         v5.102.0-rc1 -> v5.102.0-rc1
 * [new tag]         v5.245.0   -> v5.245.0
 * [new tag]         v5.246.0   -> v5.246.0
git symbolic-ref refs/git-r3/kde-frameworks/knotifications/6/__main__ refs/git-r3/HEAD
 * Checking out https://invent.kde.org/frameworks/knotifications.git to /var/tmp/portage/kde-frameworks/knotifications-9999/work/knotifications-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT NEW branch -->
   repository:               https://invent.kde.org/frameworks/knotifications.git
   at the commit:            f2a0a7cae6c5f52e5477593b4235fc5fd39b43b9
>>> Source unpacked in /var/tmp/portage/kde-frameworks/knotifications-9999/work
>>> Preparing source in /var/tmp/portage/kde-frameworks/knotifications-9999/work/knotifications-9999 ...
 * Source directory (CMAKE_USE_DIR): "/var/tmp/portage/kde-frameworks/knotifications-9999/work/knotifications-9999"
 * Build directory  (BUILD_DIR):     "/var/tmp/portage/kde-frameworks/knotifications-9999/work/knotifications-9999_build"
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/kde-frameworks/knotifications-9999/work/knotifications-9999 ...
 * Source directory (CMAKE_USE_DIR): "/var/tmp/portage/kde-frameworks/knotifications-9999/work/knotifications-9999"
 * Build directory  (BUILD_DIR):     "/var/tmp/portage/kde-frameworks/knotifications-9999/work/knotifications-9999_build"
cmake -C /var/tmp/portage/kde-frameworks/knotifications-9999/work/knotifications-9999_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DQT_MAJOR_VERSION=6 -DBUILD_QCH=no -DKDE_INSTALL_USE_QT_SYS_PATHS=ON -DKDE_INSTALL_DOCBUNDLEDIR=/usr/share/help -DCMAKE_DISABLE_FIND_PACKAGE_Qt6Qml=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/kde-frameworks/knotifications-9999/work/knotifications-9999_build/gentoo_toolchain.cmake /var/tmp/portage/kde-frameworks/knotifications-9999/work/knotifications-9999
loading initial cache file /var/tmp/portage/kde-frameworks/knotifications-9999/work/knotifications-9999_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- 

fatal: HEAD does not point to a branch
error: No such remote 'origin'
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE  
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Performing Test BSYMBOLICFUNCTIONS_AVAILABLE
-- Performing Test BSYMBOLICFUNCTIONS_AVAILABLE - Success
CMake Warning at /usr/share/ECM/modules/ECMQmlModule6.cmake:9 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find required Qt component "Qml".

  Expected Config file at "/usr/lib64/cmake/Qt6Qml/Qt6QmlConfig.cmake" exists




  Configuring with --debug-find-pkg=Qt6Qml might reveal details why the
  package was not found.

  Configuring with -DQT_DEBUG_FIND_PACKAGE=ON will print the values of some
  of the path variables that find_package uses to try and find the package.

Call Stack (most recent call first):
  /usr/share/ECM/modules/ECMQmlModule.cmake:177 (include)
  CMakeLists.txt:28 (include)


CMake Warning at /usr/share/ECM/modules/ECMQmlModule6.cmake:13 (message):
  Target Qt6::Qml was not found.  ECMQmlModule requires the QML module when
  building with Qt 6
Call Stack (most recent call first):
  /usr/share/ECM/modules/ECMQmlModule.cmake:177 (include)
  CMakeLists.txt:28 (include)


CMake Error at /usr/share/ECM/modules/ECMQmlModule.cmake:179 (message):
  Failed setting up ECMQmlModule
Call Stack (most recent call first):
  CMakeLists.txt:28 (include)


-- Configuring incomplete, errors occurred!
 * ERROR: kde-frameworks/knotifications-9999::kde failed (configure phase):
 *   cmake failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_configure
 *   environment, line 3109:  Called ecm_src_configure
 *   environment, line 1658:  Called cmake_src_configure
 *   environment, line 1302:  Called die
 * The specific snippet of code:
 *       "${CMAKE_BINARY}" "${cmakeargs[@]}" "${CMAKE_USE_DIR}" || die "cmake failed";
 * 
 * If you need support, post the output of `emerge --info '=kde-frameworks/knotifications-9999::kde'`,
 * the complete build log and the output of `emerge -pqv '=kde-frameworks/knotifications-9999::kde'`.
 * The complete build log is located at '/var/log/portage/build/kde-frameworks/knotifications-9999:20231218-052510.log.gz'.
 * For convenience, a symlink to the build log is located at '/var/tmp/portage/kde-frameworks/knotifications-9999/temp/build.log.gz'.
 * The ebuild environment file is located at '/var/tmp/portage/kde-frameworks/knotifications-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/kde-frameworks/knotifications-9999/work/knotifications-9999_build'
 * S: '/var/tmp/portage/kde-frameworks/knotifications-9999/work/knotifications-9999'
 ```

**Comment by parona-source** [comment]
git grep '$(cmake_use_find_package qml Qt6Qml)'

Only packages affected by this particular issues.

**Comment by a17r** [comment]
Any revdeps we need to take care of to drop that USEdep?

**Comment by parona-source** [comment]
I grepped for any knotifications and kitemmodels in slot 6 with the qml flag. So I shouldve updated all of them in the kde overlay.

**Comment by a17r** [comment]
Oh I see. I guess it's okay to do it like that in the overlay. I was already considering dropping these flags for packaging simplifications...

**Pull request closed without merging**
