### PR TITLE
Documentation: Add missing Qt-5.6.1 bits and regenerate files

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by johu** [comment]
What about the rest of 5.6.1 in dev-qt/? Qt should be updated properly for other consumers.

**Comment by a17r** [comment]
Could be added as well of course, this was added at first based on the old Frameworks more-deps list and now updated according to Plasma-5.6.5 autounmask needs.

Maybe just add a simple line ``dev-qt/*:5/5.6`` instead of the whole bunch?

**Comment by johu** [comment]
If the regenerate script can handle this i am fine with the proposed change.

**Comment by johu** [comment]
Thanks, picked as e00038914ab7123b4df5a2252ffb18038374b3f8.

**Pull request closed without merging**
