### PR TITLE
Adjust my email

### PR DESCRIPTION
**Pull request by Vindex17**

### CODE REVIEW

**Comment by kensington** [comment]
Documentation/CONTRIBUTORS is auto-generated based on git log, so .mailmap would need updating or this change will be reverted when regenerate-files is next run.

**Comment by Vindex17** [comment]
I'm not in .mailmap

**Comment by Vindex17** [comment]
Ah ok, I think I figured out what you mean

**Comment by kensington** [comment]
Thanks, applied.

**Pull request closed without merging**
