### PR TITLE
[net-irc/konversation] 1.6 version bump

### PR DESCRIPTION
**Pull request by a17r**
Package-Manager: portage-2.2.18

### CODE REVIEW

**Comment by mrueg** [comment]
Please also drop "1.6" from your commit msg

**Comment by a17r** [comment]
configure checks for Qca-qt5, not openssl - to be sure I also rebuilt it with qca:2[-openssl] successfully

**Comment by kensington** [comment]
Indeed - most of the qca USE flags are for runtime plugins (replacing the old eg. app-crypt/qca-ossl).

**Comment by mrueg** [comment]
Merged, thanks!

**Pull request merged**
